# Generated by Django 4.2.6 on 2023-10-28 04:12

from django.db import migrations, models
import django.db.models.deletion
import webinfoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webinfoapp', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': [('add_device_model', 'Can add device'), ('change_device_model', 'Can change device'), ('delete_device_model', 'Can delete device')]},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'permissions': [('add_platform_model', 'Can add platform'), ('change_platform_model', 'Can change platform'), ('delete_platform_model', 'Can delete platform')]},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('add_product_model', 'Can add product'), ('change_product_model', 'Can change product'), ('delete_product_model', 'Can delete product')]},
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[webinfoapp.models.validate_ip_address]),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='webinfoapp.platform'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='webinfoapp.product'),
        ),
    ]
