# Generated by Django 4.2.6 on 2023-10-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinfoapp', '0005_alter_device_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinfoapp.platform'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinfoapp.product'),
        ),
    ]
