# Generated by Django 4.2.6 on 2023-10-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinfoapp', '0008_administrator_technician_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
